/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facecloud_FaceCloudLib */

#ifndef _Included_com_facecloud_FaceCloudLib
#define _Included_com_facecloud_FaceCloudLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_facecloud_FaceCloudLib_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    Calculate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_facecloud_FaceCloudLib_Calculate
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    LoadJsonStringFromFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_facecloud_FaceCloudLib_LoadJsonStringFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    SaveFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_facecloud_FaceCloudLib_SaveFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
