/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_facecloud_FaceCloudLib.h"
#include "FaceCloudLib.h"
#include "json/json.h"
/* Header for class com_facecloud_FaceCloudLib */

#ifdef __cplusplus
extern "C" {
#endif


	FaceCloudLib gFaceCloudLib;


	std::string jstring2string(JNIEnv *env, jstring jStr) {
		if (!jStr)
			return "";

		const jclass stringClass = env->GetObjectClass(jStr);
		const jmethodID getBytes = env->GetMethodID(stringClass, "getBytes", "(Ljava/lang/String;)[B");
		const jbyteArray stringJbytes = (jbyteArray)env->CallObjectMethod(jStr, getBytes, env->NewStringUTF("UTF-8"));

		size_t length = (size_t)env->GetArrayLength(stringJbytes);
		jbyte* pBytes = env->GetByteArrayElements(stringJbytes, NULL);

		std::string ret = std::string((char *)pBytes, length);
		env->ReleaseByteArrayElements(stringJbytes, pBytes, JNI_ABORT);

		env->DeleteLocalRef(stringJbytes);
		env->DeleteLocalRef(stringClass);
		return ret;
	}
/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_facecloud_FaceCloudLib_Init	(JNIEnv *, jobject)
{
	return gFaceCloudLib.Init(false);
}

/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    Calculate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_com_facecloud_FaceCloudLib_Calculate
(JNIEnv * env, jobject jobj, jstring jmodelID, jstring jjsonFace, jstring jphotoPath, jstring jphotoPathOut)
{
	string finalPathout;
	string ret;
	string photoPathOut = jstring2string(env, jphotoPathOut);
	ret = gFaceCloudLib.Calculate(jstring2string(env, jmodelID), jstring2string(env, jjsonFace), jstring2string(env, jphotoPath), photoPathOut,finalPathout);
	return env->NewStringUTF(ret.c_str());
}

/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    LoadJsonStringFromFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_facecloud_FaceCloudLib_LoadJsonStringFromFile
(JNIEnv * env, jobject jobj, jstring filepath)
{
	string path = jstring2string(env, filepath);
	//printf("Java_com_facecloud_FaceCloudLib_LoadJsonStringFromFile : %s" ,path.c_str());
	string rt = gFaceCloudLib.LoadJsonStringFromFile(path);
	return env->NewStringUTF(rt.c_str());
}

/*
 * Class:     com_facecloud_FaceCloudLib
 * Method:    SaveFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_facecloud_FaceCloudLib_SaveFile
(JNIEnv * env, jobject jobj, jstring js, jstring jpath)
{
	string s = jstring2string(env, js);
	string path = jstring2string(env, jpath);
	gFaceCloudLib.SaveFile(s,path);
}

#ifdef __cplusplus
}
#endif
